### ISSUE TITLE
Issue running demo script

### ISSUE THREAD

**Issue by nshreyasvi** [karShetty/PLIKS#5]
Hello,
Thank you for your great work. I was trying to run the demo script but was getting the following error:
```demo/input/000000061418.png libcudart.so.10.1: cannot open shared object file: No such file or directory```
I have installed cuda toolkit as well as pytorch with cuda. When I used `nvcc --version` it shows the 11.8 and also when I do `torch.version.cuda` and `torch.cuda.is_available()` which returns `True`.
Could you let me know how to resolve this issue?

**Comment by karShetty** [comment]
This means your torch is running on Cuda 10.1 but you have CUDA 11.8 installed. You could try reinstalling torch in a new venv for any specific [torch version / cuda toolkit](https://pytorch.org/get-started/previous-versions/)

**Comment by nshreyasvi** [comment]
Hello, Thank you so much, I managed to solve the issue but when I run the demo script I get the following error

```
Expected size for first two dimensions of batch2 tensor to be: [1, 40] but got: [30, 40].
```

I use the command:
```
python demo.py --img_dir demo/input/000000296657.png --out_dir demo/output/ --checkpoint checkpoint_sparse.pt --model MeshRegSparse
```

Could you let me know what might be the issue here?

**Comment by nshreyasvi** [comment]
Hello, sorry for the delays. I was able to resolve the issues and render the output meshes. I changed line 130 in `pliks/utils.py` to the following:
```
def vtk_write(path, polydata, type='obj'):
```
and uncommented line 157 and 158 changing them as 
```
vtk_write(os.path.join(self.options.out_dir, out_name + '_res_%02d.obj') % (_i,),
          create_polydata(pred_vK[0].cpu().data.numpy(), self.smpl.faces.cpu().data.numpy()))
```
so that I can save the output `.obj` files. 
 
but would like to know how can I save the output in `.pkl` format with `global_pose` and other keys?
